project_id = "uvnmahblsafibjgdfjfg"

[functions.ai-generate]
verify_jwt = false

[functions.ai-improve]
verify_jwt = false

[functions.ai-tailor]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-ats-score]
verify_jwt = false
